name: pull_request

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build the Docker image (PR)
      env:
        # not accepted as the repo contains uppercase letters
        #REPO_NAME: ${{ github.event.repository.name }}
        REPO_NAME: pi_udbenchmark
        REPO_BRANCH: ${{ github.head_ref }}
      run: docker build . --file Dockerfile --tag $REPO_NAME:$REPO_BRANCH

    - name: Get the docker image testing material
      run:  wget -O test_docker_call.py https://raw.githubusercontent.com/eurobench/docker_test/master/test_docker_call.py

    - name: test the docker image
      env:
        TEST_PLAN: tests/test_plan.xml
        # not accepted as the repo contains uppercase letters
        #DOCKER_IMAGE: ${{ github.event.repository.name }}:${{ github.head_ref }}
        DOCKER_IMAGE: pi_udbenchmark:${{ github.head_ref }}
      run:  python3 test_docker_call.py
